config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'index' => 'home#index'
  get 'quote' => 'home#quote'
  get 'corporate' => 'home#corporate'
  get 'residential' => 'home#residential'
  get 'login' => 'home#login'
  get 'thankyou' => 'home#thankyou'
  post 'home', to: "home#create"
  post 'leads', to: "leads#create"
  get '404' => 'home#404'
  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
    get 'intervention' => 'intervention#intervention'
  end
  
  
  
  #devise_for :users

  ActiveAdmin.routes(self)

  #Devise
  



  devise_for :users
  devise_scope :user do
    get '/users/sign_in' => 'devise/session#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  # devise_for :users, ActiveAdmin::Devise.config
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path' => redirect('/404')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def residential
  end

  def corporate
  end

  def quote
  end


  def create
    buildingType = params[:tipe]
    
    if buildingType == "residential"
      Quote.create(
        Product_Quality: params[:price],
        Building_Type: params[:tipe],
        Nb_Appartement: params[:numDoor],
        Nb_Floor: params[:numFloor],
        Nb_Basement: params[:numBasement],
        Price_Per_Ele: params[:pricePerElevator],
        Subtotal: params[:finalPriceElevator],
        Nb_Ele_Suggested: params[:finalNumberElevator],
        Install_Fee: params[:finalInstalationFee],
        Final_Price: params[:finalTotalPrice],
        Full_Name: params[:fullName],
        Phone_Number: params[:phoneNumber],
        Company_Name: params[:comName],
        Email: params[:email]
       )






    elsif buildingType == "commercial"
        puts "commercial"
      Quote.create(
        Product_Quality: params[:price],
        Building_Type: params[:tipe],
        Nb_Business: params[:numDoor],
        Nb_Floor: params[:numFloor],
        Nb_Basement: params[:numBasement],
        Nb_Parking: params[:numParking],
        Nb_Cage: params[:numDemand],
        Price_Per_Ele: params[:pricePerElevator],
        Subtotal: params[:finalPriceElevator],
        Nb_Ele_Suggested: params[:finalNumberElevator],
        Install_Fee: params[:finalInstalationFee],
        Final_Price: params[:finalTotalPrice],
        Full_Name: params[:fullName],
        Phone_Number: params[:phoneNumber],
        Company_Name: params[:comName],
        Email: params[:email]
       )
    elsif buildingType == "corporate"
      puts "corporate"
      Quote.create(
        Product_Quality: params[:price],
        Building_Type: params[:tipe],
        Nb_Company: params[:numDoor],
        Nb_Floor: params[:numFloor],
        Nb_Basement: params[:numBasement],
        Nb_Parking: params[:numParking],
        Nb_OccupantPerFloor: params[:numMPF],
        Price_Per_Ele: params[:pricePerElevator],
        Subtotal: params[:finalPriceElevator],
        Nb_Ele_Suggested: params[:finalNumberElevator],
        Install_Fee: params[:finalInstalationFee],
        Final_Price: params[:finalTotalPrice],
        Full_Name: params[:fullName],
        Phone_Number: params[:phoneNumber],
        Company_Name: params[:comName],
        Email: params[:email]
       )
    else
      puts "hybrid"
      Quote.create(
        Product_Quality: params[:price],
        Building_Type: params[:tipe],
        Nb_Business: params[:numDoor],
        Nb_Floor: params[:numFloor],
        Nb_Basement: params[:numBasement],
        Nb_Parking: params[:numParking],
        Nb_OccupantPerFloor: params[:numMPF],
        Nb_OperatingHour: params[:numActiveHour],
        Price_Per_Ele: params[:pricePerElevator],
        Subtotal: params[:finalPriceElevator],
        Nb_Ele_Suggested: params[:finalNumberElevator],
        Install_Fee: params[:finalInstalationFee],
        Final_Price: params[:finalTotalPrice],
        Full_Name: params[:fullName],
        Phone_Number: params[:phoneNumber],
        Company_Name: params[:comName],
        Email: params[:email]
       )
    end
    ZendeskAPI::Ticket.create!($client, :type => "task", :subject => "#{params[:fullName]} from #{params[:comName]}", :comment => { :value => "
      The contact #{params[:fullName]} from company #{params[:comName]} can be reached at email  #{params[:email]} and at 
      phone number #{params[:phoneNumber]}. #{params[:fullName]} want a total of #{params[:finalNumberElevator]} #{params[:price]} elevators. 
      The subtotal is: #{params[:finalPriceElevator]}, instalation fee is: #{params[:finalInstalationFee]} and the total quote price is: #{params[:finalTotalPrice]}" }, :priority => "urgent") 
    redirect_to "/thankyou"

  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/404.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .rails-default-error-page {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  .rails-default-error-page div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  .rails-default-error-page div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  .rails-default-error-page h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  .rails-default-error-page div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body class="rails-default-error-page">
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div class="text-center" style="padding-top: 250px;">
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
  </div>
</body>
</html>

app/views/home/corporate.html.erb
		
			
		
			<section class="fullwidthbanner-container">
				<%= image_tag("CorporateHome.jpeg", :style => "width:100%;filter: brightness(50%)", :alt => "", :class => "fullwidth,  ") %>
			</section>
			<!-- /Residential Home -->

			<!-- Welcome -->
			<section>
				<div class="container">


					<div class="text-center">
						<h1>Welcome dear <span>clients</span>, to our commercial & corporate products.</h1>
						<h2 class="col-sm-10 offset-sm-1 mb-0 fw-400">Take a look at our trendy, quiet & peaceful products.</h2>
					</div>

				</div>
			</section>
			<!-- Welcome -->


<!-- Services -->
<section id="services">
	<div class="container">
		<div class="heading-title heading-dotted text-center">
			<h2>Our Commercial and Corporate Products</h2>
		</div>

		<div class="row">
			<div class="col-sm-4">
				<%= image_tag("CorporateHydraulic.jpeg", :alt => "", :width => "300", :height => "300") %>
				<h3 class="mt-10"> Hydraulic Elevators</h3>
				<p>Hydraulic systems have a fluid-driven piston mounted inside of a cylinder that lifts the cab. These elevators are best for low-rise buildings no more than five stories tall. </p>
				<a href="https://www.ascensionelevators.com/services/types-advantages-of-roped-hydraulic-elevator-systems/" class="btn btn-info">Get more info</a>
				
			</div>

			<div class="col-sm-4">
				<%= image_tag("MachineRoomLess.jpg", :alt => "", :width => "300", :height => "300") %>
				<h3 class="mt-10"> Machine Room-Less </h3>
				<p>Either traction or hydraulic, MRL commercial elevators don’t require a machine room. This can create more space in your building and requires less energy to operate.

				</p>
				<a href="https://www.vacuumelevators.com/principles-components/" class="btn btn-info">Get more info</a>
			</div>

			<div class="col-sm-4">
				<%= image_tag("Traction.jpg", :alt => "", :width => "300", :height => "300") %>
				<h3 class="mt-10">Traction  Elevators </h3>
				<p>Traction elevators are the most common type of elevators. Elevator cars are pulled up by means of rolling steel ropes over a deeply grooved pulley, commonly called a sheave in...
				</p>
				<a href="https://elevation.fandom.com/wiki/Traction_elevators" class="btn btn-info">Get more info</a>
			</div>

		</div>

	</div>
</section>
<!-- /Services -->




<!-- FOOTER -->
<footer id="footer">
	<div class="container">


		<div class="row">

			<!-- col #1 -->
			<div class="col-md-8">

				<h3 class="letter-spacing-1">WHY US?</h3>

				<!-- Small Description -->
				<p>
					Rocket Elevators is offering you the best elevators and services that you can find on the market. Also, our prices are inevitably unbeatable .
				</p>
				<h2>1(581) 701-0303</h2>
			</div>
			<!-- /col #1 -->

			<!-- col #2 -->
			<div class="col-md-4">
				<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

				<!-- Newsletter Form -->
				<p>Subscribe to Our Newsletter to get Important News & Offers</p>

				<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
						<input type="email" id="email" name="email2" class="form-control required" placeholder="Enter your Email">
						<span class="input-group-btn">
							<a href="thankyou" class="btn btn-success">Subscribe</a>
						</span>
					</div>
				</form>
				<!-- /Newsletter Form -->


			</div>
			<!-- /col #2 -->

		</div>


	</div>

	<div class="copyright">
		<div class="container">
			<ul class="float-right m-0 list-inline mobile-block">

				<style>
					/* Popup container - can be anything you want */
					.popup {
					  position: relative;
					  display: inline-block;
					  cursor: pointer;
					  -webkit-user-select: none;
					  -moz-user-select: none;
					  -ms-user-select: none;
					  user-select: none;
					}
					
					/* The actual popup */
					.popup .popuptext {
					  visibility: hidden;
					  width: 160px;
					  background-color: #555;
					  color: #fff;
					  text-align: center;
					  border-radius: 6px;
					  padding: 8px 0;
					  position: absolute;
					  z-index: 1;
					  bottom: 125%;
					  left: 50%;
					  margin-left: -80px;
					}
					
					/* Popup arrow */
					.popup .popuptext::after {
					  content: "";
					  position: absolute;
					  top: 100%;
					  left: 50%;
					  margin-left: -5px;
					  border-width: 5px;
					  border-style: solid;
					  border-color: #555 transparent transparent transparent;
					}
					
					/* Toggle this class - hide and show the popup */
					.popup .show {
					  visibility: visible;
					  -webkit-animation: fadeIn 1s;
					  animation: fadeIn 1s;
					}
					
					/* Add animation (fade in the popup) */
					@-webkit-keyframes fadeIn {
					  from {opacity: 0;} 
					  to {opacity: 1;}
					}
					
					@keyframes fadeIn {
					  from {opacity: 0;}
					  to {opacity:1 ;}
					}
					</style>
				<li><div class="popup" onclick="myFunction()">Terms &amp; Conditions
				<span class="popuptext" id="myPopup">Other than the content you own, under these Terms, Company Name and/or its licensors own all the intellectual property rights and materials contained in this Website.<br>You are granted limited license only for purposes of viewing the material contained on this Website.</span>
				</div></li>
					<li></li>
					<li></li>
					<li>&bull;</li>
					<li></li>
					<li></li>
				<li><div class="popup" onclick="pop2()">Privacy
				<span class="popuptext" id="popMy">Log and usage data. We may log information when you access and use the Services.<br> This may include your IP address, user-agent string, browser type, operating system, referral URLs, device information (e.g., device IDs), pages visited, links clicked, the requested URL, hardware settings, and search terms. <br> Except for the IP address used to create your account, Rocket Elevators Ltd will delete any IP addresses collected after 100 days.</span>
				</div></li>
			</ul>
			&copy; All Rights Reserved, Company LTD
		</div>
	</div>

</footer>
<!-- /FOOTER -->

		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>
		<!-- POPUP SCRIPTS -->
		<script>
			// When the user clicks on div, open the popup
				function myFunction() {
				var popup = document.getElementById("myPopup");
				popup.classList.toggle("show");
			}
			// When the user clicks on div, open the popup
			function pop2() {
				var popup = document.getElementById("popMy");
				popup.classList.toggle("show");
			}
		</script>
		<script>var plugin_path = 'assets/plugins/';</script>
		<%= javascript_include_tag 'contact', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'scripts', media: 'all', 'data-turbolinks-track': 'reload' %>

	</body>
</html>

app/views/home/quote.html.erb
			<script src="https://www.google.com/recaptcha/api.js" async defer></script>

			<%= form_tag home_path, :id => 'elm_id' do %>
				<div class="text-center ">
					<div class="m-20">
						<div class="select-rm">
								<input  type="button" class="btn btn-default build-type" id="buildingResidential" value="residential" name="typeBuilding">
								<input  type="button" class="btn btn-default build-type" id="buildingCommercial" value="commercial" name="typeBuilding">
								<input  type="button" class="btn btn-default build-type" id="buildingCorporate" value="corporate" name="typeBuilding">
								<input  type="button" class="btn btn-default build-type" id="buildingHybrid" value="hybrid" name="typeBuilding">
								<input  type="hidden" id="resultBuilding" name="tipe">
						</div>
					</div>
				</div>

					

				<div class="container" >
					<div class="row q-hide" id="q-door">
						<div class="col-6 text-right">
							<p id="numDoorText">Number of appartment</p>
						</div>
						<div class="col-6 text-left">
							<input id="numDoor" class="ml-20 q-press everything" type="number" min="0" name="numDoor">
						</div>
					</div>
				</div>




				<div class="container">
					<div class="row q-hide" id="q-floor">
						<div class="col-6 text-right">
							<p id="numFloorText">Number of floor</p>
						</div>
						<div class="col-6 text-left">
							<input id="numFloor" class="ml-20 q-press everything" type="number" min="0" name="numFloor">
						</div>
					</div>
				</div>




				<div class="container" >
					<div class="row q-hide" id="q-basement">
						<div class="col-6 text-right">
							<p id="numBasementText">Number of Basement</p>
						</div>
						<div class="col-6 text-left">
							<input id="numBasement" class="ml-20 q-press everything" type="number" min="0" name="numBasement">
						</div>
					</div>
				</div>




				<div class="container" >
					<div class="row q-hide" id="q-parking">
						<div class="col-6 text-right">
							<p id="numParkingText">Number of Parking</p>
						</div>
						<div class="col-6 text-left">
							<input id="numParking" class="ml-20 q-press everything" type="number" min="0" name="numParking">
						</div>
					</div>
				</div>


				<div class="container" >
					<div class="row q-hide" id="q-maxPerson">
						<div class="col-6 text-right">
							<p id="numMaxPersonFloorText">Number of Maximum Person per Floor</p>
						</div>
						<div class="col-6 text-left">
							<input id="numMaxPersonFloor" class="ml-20  q-press everything" type="number" min="0" name="numMPF">
						</div>
					</div>
				</div>


				<div class="container" >
					<div class="row q-hide" id="q-hour">
						<div class="col-6 text-right">
							<p id="numActiveHourText">Number of Active Hours</p>
						</div>
						<div class="col-6 text-left">
							<input id="numActiveHour" class="ml-20  q-press everything" type="number" min="0" max="24" name="numActiveHour">
						</div>
					</div>
				</div>


				<div class="container" >
					<div class="row q-hide" id="q-demand">
						<div class="col-6 text-right">
							<p id="numDemandText">Number of Elevator Wanted</p>
						</div>
						<div class="col-6 text-left">
							<input id="numDemand" class="ml-20 q-press everything" type="number" min="0" name="numDemand">
						</div>
					</div>
				</div>

					
					

				
				<div class="text-center mt-30 ">
					<h3>Model of elevator</h3>
				</div>
				


				


				
				<div class="alternate pt-30">
					<div class="container text-center ">
						<div class="row">
							<div class="col-5 radio-hide" id="q-maxPerson">
								<div>
									
									<label class="mb-20">Standard
									<input id="radioStandard" class="radio-price ml-8" type="radio" name="price" value="Standard"></label>
									<p style="font-size: 12px;">Price per unit is: 7'565.00$<br>
										Installation fee is: 10%
									</p>
									
								</div>
							</div>
						
						
							<div class="col-2 radio-hide" id="q-maxPerson">
								<div>
									<label class="mb-20">Premium
									<input id="radioPremium" class="radio-price ml-8" type="radio" name="price" value="Premium"></label>
									<p style="font-size: 12px;">Price per unit is: 12'345.00$<br>
										Installation fee is: 13%
									</p>
								</div>
							</div>
						
							<div class="col-5 radio-hide " id="q-maxPerson">
								<div>
									<label class="mb-20">Excelium
									<input id="radioExcelium" class="radio-price ml-8" type="radio" name="price" value="Excelium"></label>
									<p style="font-size: 12px;">Price per unit is: 15'400.00$<br>
										Installation fee is: 16%
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
				<br>
				<div class="text-center mt-30 ">
					<h3>Our suggestion and price</h3>
					<hr>
				</div>
				<div class="text-center">
					<div class="container">
						<div class="row">
							<h4 class="col-6 q-final everything" id="fPriceElev">Price of elevator: </h4>
							<input  type="hidden" id="finalPriceElevator" name="finalPriceElevator">

							<h4 class="col-6 q-final everything" id="fNumElev">Number of Elevator sugested: </h4>
							<input  type="hidden" id="finalNumElev" name="finalNumberElevator">
						</div>
						<div class="row">
							<h4 class="col-6 q-final everything" id="fInstPrice">Instalation fee: </h4>
							<input  type="hidden" id="finalInstalationFee" name="finalInstalationFee">

							<h4 class="col-6 q-final everything" id="fNumColumn">Number of Column needed: </h4>
							<input  type="hidden" id="finalColumn" name="finalColumn">
						</div>
						<div class="row">
							<h4 class="col-6 q-final everything" id="fTotalPrice">Total price: </h4>
							<input  type="hidden" id="finalTotalPrice" name="finalTotalPrice">

							<h4 class="col-6 q-final everything" id="fNumElevColumn">Number of elevator per Column: </h4>
							<input  type="hidden" id="finalNumberElevatorColumn" name="finalNumberElevatorColumn">
							<input type="hidden" id="pricePerElevator" name="pricePerElevator">
						</div>
					</div>
            	</div>
				<div class="text-center">
					<div class="row pt-20">
						<div class="col-6">
							<label class="hide-end" for="fullName">Full Name: <input class="everything" id="fullName" type="text" name="fullName"></label>
							
						</div>
						<div class="col-6">
							<label class="hide-end" for="phoneNumber">Phone Number: <input class="everything" id="phoneNumber" type="text" name="phoneNumber"></label>
							
						</div>
					</div>
					<div class="row">
						<div class="col-6">
							<label class="hide-end" for="comName">Company Name: <input class="everything" id="comName" type="text" name="comName"></label>
							
						</div>
						<div class="col-6">
							<label class="hide-end" for="email">Email: <input class="everything" id="email" type="text" name="email"></label>
							
						</div>
					</div>
					<div class="row pt-20">
						<div class="col-3">
						</div>
						<div class="hide-end col-2 g-recaptcha" data-sitekey="<%=ENV["RECAPTCHA_SITE_KEY"]%>" data-callback="recaptchaCallback">
							
						</div>
						<div class="col-2">
							<div class="actions">
								<button class="hide-end btn btn-dark btn-lg mt-12" id="submitBtn" disabled>Submit</button>
							</div>
						</div>
						<div class="col-5">
						</div>
					</div>
				
				</div>
			<% end %>

				<!-- CONTACT -->
				<section id="Call">
					<div class="container">
						<header class="text-center mb-60">
							<h2>Contact Us</h2>
							<p class="lead font-lato">You have a question? You would like more informations? Our phone service's is available 24/7.</p>
							<a class="btn btn-secondary" href="#phone"> Contact us <i class="fa fa-angle-right"></i></a>
							<hr />
						</header>
					</div>
				</section>
				
			<!-- /CONTACT -->
	



			<!-- FOOTER -->
			<footer id="footer">
				<div class="container">


					<div class="row">

						<!-- col #1 -->
						<div id="phone" class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
								Rocket Elevators is offering you the best elevators and services that you can find on the market. Our employees work for your satisfaction and are there to answer your questions. Also, our prices are inevitably unbeatable .
							</p>
							<h2>1(581) 701-0303</h2>
						</div>
						<!-- /col #1 -->

						<!-- col #2 -->
						<div class="col-md-4">
							<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

							<!-- Newsletter Form -->
							<p>Subscribe to Our Newsletter to get Important News & Offers</p>

							<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
									<span class="input-group-btn">
										<a href="thankyou" class="btn btn-success">Subscribe</a>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->


						</div>
						<!-- /col #2 -->

					</div>


				</div>

			<!-- Terms and Privacy -->
			<div class="copyright">
				<div class="container">
					<ul class="float-right m-0 list-inline mobile-block">
		
						<style>
							/* Popup container - can be anything you want */
							.popup {
							  position: relative;
							  display: inline-block;
							  cursor: pointer;
							  -webkit-user-select: none;
							  -moz-user-select: none;
							  -ms-user-select: none;
							  user-select: none;
							}
							
							/* The actual popup */
							.popup .popuptext {
							  visibility: hidden;
							  width: 160px;
							  background-color: #555;
							  color: #fff;
							  text-align: center;
							  border-radius: 6px;
							  padding: 8px 0;
							  position: absolute;
							  z-index: 1;
							  bottom: 125%;
							  left: 50%;
							  margin-left: -80px;
							}
							
							/* Popup arrow */
							.popup .popuptext::after {
							  content: "";
							  position: absolute;
							  top: 100%;
							  left: 50%;
							  margin-left: -5px;
							  border-width: 5px;
							  border-style: solid;
							  border-color: #555 transparent transparent transparent;
							}
							
							/* Toggle this class - hide and show the popup */
							.popup .show {
							  visibility: visible;
							  -webkit-animation: fadeIn 1s;
							  animation: fadeIn 1s;
							}
							
							/* Add animation (fade in the popup) */
							@-webkit-keyframes fadeIn {
							  from {opacity: 0;} 
							  to {opacity: 1;}
							}
							
							@keyframes fadeIn {
							  from {opacity: 0;}
							  to {opacity:1 ;}
							}
							</style>
						<li><div class="popup" onclick="myFunction()">Terms &amp; Conditions
						<span class="popuptext" id="myPopup">Other than the content you own, under these Terms, Company Name and/or its licensors own all the intellectual property rights and materials contained in this Website.<br>You are granted limited license only for purposes of viewing the material contained on this Website.</span>
							</div></li>
							<li></li>
							<li></li>
							<li>&bull;</li>
							<li></li>
							<li></li>
						<li><div class="popup" onclick="pop2()">Privacy
						<span class="popuptext" id="popMy">Log and usage data. We may log information when you access and use the Services.<br> This may include your IP address, user-agent string, browser type, operating system, referral URLs, device information (e.g., device IDs), pages visited, links clicked, the requested URL, hardware settings, and search terms. <br> Except for the IP address used to create your account, Rocket Elevators Ltd will delete any IP addresses collected after 100 days.</span>
						</div></li>
					</ul>
					&copy; All Rights Reserved, Company LTD
				</div>
			</div>

		<!-- /Terms and Privacy -->
			</footer>
			<!-- /FOOTER -->

		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>


		<script type="text/javascript">
			var recaptchachecked;
			function recaptchaCallback() {
				$("#submitBtn").removeClass("btn-dark");
				$('#submitBtn').removeAttr('disabled');
            	$("#submitBtn").addClass("btn-primary");
				
				//If we managed to get into this function it means that the user checked the checkbox.
				recaptchachecked = true;
			}
		</script>
		<!-- POPUP SCRIPTS -->
		<script>
			// When the user clicks on div, open the popup
				function myFunction() {
				var popup = document.getElementById("myPopup");
				popup.classList.toggle("show");
			}
			// When the user clicks on div, open the popup
			function pop2() {
				var popup = document.getElementById("popMy");
				popup.classList.toggle("show");
			}
		</script>
		<script>var plugin_path = 'assets/plugins/';</script>
		<%= javascript_include_tag 'contact', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'scripts', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'QuoteForm', media: 'all', 'data-turbolinks-track': 'reload' %>
	</body>
</html>

app/views/home/thankyou.html.erb
<!-- THEME CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<div class="jumbotron text-center">
    <h1 class="display-3">Thank you, we received all of the information correctly!</h1>
    <hr>
    <p>
      Having trouble? <a href="index#contact">Contact us</a>
    </p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="index" role="button">Continue to Homepage</a>
    </p>
  </div>
  <script>var plugin_path = 'assets/plugins/';</script>
  <%= javascript_include_tag 'contact', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'scripts', media: 'all', 'data-turbolinks-track': 'reload' %>

<style>
    
</style>