config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'index' => 'home#index'
  get 'quote' => 'home#quote'
  get 'corporate' => 'home#corporate'
  get 'residential' => 'home#residential'
  get 'login' => 'home#login'
  get 'thankyou' => 'home#thankyou'
  post 'home', to: "home#create"
  post 'leads', to: "leads#create"
  get '404' => 'home#404'
  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
    get 'intervention' => 'intervention#intervention'
  end
  
  
  
  #devise_for :users

  ActiveAdmin.routes(self)

  #Devise
  



  devise_for :users
  devise_scope :user do
    get '/users/sign_in' => 'devise/session#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  # devise_for :users, ActiveAdmin::Devise.config
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path' => redirect('/404')
end

app/models/WarehouseBase.rb
class WarehouseBase < ActiveRecord::Base
    establish_connection DB_SECOND
    self.abstract_class = true
  end

app/models/address.rb
class Address < ApplicationRecord
    require 'google_maps_service'
    has_many :building, dependent: :destroy
    has_many :customer, dependent: :destroy
    
    before_update :coords_update
    before_create :coords_update
    def coords_update
        gmaps = GoogleMapsService::Client.new(key: "#{ENV['GOOGLE_API']}")
        results = gmaps.geocode("#{self.number_and_street},#{self.city}, #{self.country}")
        self.latitude = results[0][:geometry][:location][:lat]
        self.longitude =  results[0][:geometry][:location][:lng]
        if results[0][:address_components][5] != nil
            self.state = results[0][:address_components][5][:short_name]
        end
        if results[0][:address_components][7] != nil 
            self.postal_code = results[0][:address_components][7][:short_name]

        end
        if results[0][:address_components][6] != nil
            self.country = results[0][:address_components][6][:short_name]
        end
        if results[0][:address_components][2] != nil
            self.city = results[0][:address_components][2][:long_name]
        end
    end
end

app/models/battery.rb
class Battery < ApplicationRecord
    has_many :column, dependent: :destroy
    belongs_to :building, optional: true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :battery, dependent: :destroy
    has_many :building_details, dependent: :destroy
    belongs_to :address, optional: true
    belongs_to :customer, optional: true
end

app/models/chart.rb
class Chart < ApplicationRecord
end

app/models/column.rb
class Column < ApplicationRecord
    has_many :elevator, dependent: :destroy
    belongs_to :battery, optional: true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :address, optional: true
    has_many :building, dependent: :destroy
end

app/models/dim_customers.rb
class DimCustomers < WarehouseBase
end

app/models/elevator.rb
require './lib/tasks/send_sms.rb'
require 'slack-notifier'
require 'dotenv'
class Elevator < ApplicationRecord
    belongs_to :column, optional: true
    after_update :send_sms
    
    before_update :slack_notifier

    def send_sms()
      $currentElevatorID = self.id
      $currentElevatorStatus = self.status
      if $currentElevatorStatus.downcase == 'intervention'
          sms = Messenger::SMS.new
          sms.send_sms
      end
    end



    def slack_notifier
        if self.status_changed?
          require 'date'
          current_time = DateTime.now.strftime("%d-%m-%Y %H:%M")
          notifier = Slack::Notifier.new ENV["SLACK_API_WEBHOOK_URL"]  do
            defaults channel: "#elevator_operations"
          end
          notifier.ping "The Elevator #{self.id} with Serial Number #{self.serial_number} changed status from #{self.status_was} to #{self.status} at #{current_time}."
        end
    end
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  belongs_to :user, optional: true
end

app/models/fact_contact.rb
class FactContact < WarehouseBase
#  belongs_to: RocketApp_second_development
end

app/models/fact_elevator.rb
class FactElevator < WarehouseBase
end

app/models/fact_quote.rb
class FactQuote < WarehouseBase
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord

end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :employee, dependent: :destroy

end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/admin/dashboard/_google_map.html.erb
<div id="map" style="width: 100%; height: 600px;"></div>
<div class="testing"></div>
<script async defer

        src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API']%>&callback=initMap&libraries=&v=weekly"
></script>
<script type="text/javascript">
    var map;
    function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: 34.2392116, lng: -84.19558549999999 },
        zoom: 8
    });
    
    <% Building.all.each do |building| 
        nbElevators = 0 
        nbColumn = 0
        nbFloor = 0
        nbBattery = building.battery.count
        building.battery.all.each do |battery|
            nbColumn += battery.column.count
            battery.column.all.each do |column|
                nbFloor = column.number_of_floors
                nbElevators += column.elevator.count
            end
        end 
        
        if nbBattery == 0 %>
            var markers = 
            {
                coords:{lat: <%= building.address.latitude%>, lng: <%= building.address.longitude %>},
                content:'<h6><%=building.address.number_and_street%><br><br>Client name: <%=building.admin_full_name%>.<br><br>This is the home address of the client<br><br>',
            }
            addMarker(markers, <%=nbBattery%>)
        <%    next
        else %>
        var markers = 
            {
                coords:{lat: <%= building.address.latitude%>, lng: <%= building.address.longitude %>},

                content:'<h6><%=building.address.number_and_street%><br><br>Number of floors: <%=nbFloor%>.<br><br>Client name: <%=building.admin_full_name%>.<br><br>Number of Batteries: <%=nbBattery%>.<br><br>Number of Columns: <%=nbColumn%>.<br><br>Number of Elevators: <%=nbElevators%>.<br><br>Full name of technical contact: <%=building.full_name_STA%><br><br>',

            }
        addMarker(markers, <%=nbBattery%>)
        
        
       
    <% 
        end  
    end %>
    
    function weatherBalloon( lat, lon, point) {
        var key = '<%= ENV['OPEN_WEATHER_API'] %>';
        fetch('https://api.openweathermap.org/data/2.5/weather?lat=' + lat + '&lon=' + lon + '&appid=' + key + '&units=metric')  
        .then(function(resp) { return resp.json() }) // Convert data to json
        .then(function(data) {
        console.log(data.main.temp);
        console.log("BEans")
        console.log(point.content)
        var get_content = point.content
        console.log(get_content)
        point.setContent( get_content + "Temperature: " + data.main.temp + " °C </h6>")
        })
        .catch(function(bat) {
            console.log(bat)
        // catch any errors
        });
    }

    function addMarker(props, nbBatt){
        if (nbBatt == 0) {
            var marker = new google.maps.Marker({
                position:props.coords,
                map:map,
                icon: "<%= ActionController::Base.helpers.image_url('client_house.png') %>",
            });
        }else {
            var marker = new google.maps.Marker({
                position:props.coords,
                map:map,
                icon: "<%= ActionController::Base.helpers.image_url('favicon.png') %>",
            });
        }
        
        // Check content
        if(props.content){

        let infoWindow
          marker.addListener('click', function(){
            if (infoWindow !== undefined){
                infoWindow.close();
            }
            infoWindow = new google.maps.InfoWindow({
            content:props.content
          });
            weatherBalloon(marker.getPosition().lat(), marker.getPosition().lng(), infoWindow)
            infoWindow.open(map, marker);
          });
        }
      }
    }

</script>


        <%# window.onload = function() {
        weatherBalloon( 6167865 ); %>

app/views/admin/dashboard/_ibm_watson.html.erb
  <% # Generate Watson TTS
  require 'zendesk_api'
  require "ibm_watson/authenticators"
  require "ibm_watson/text_to_speech_v1"
  totalQuotes = 0
  totalLeads = 0
  $client.tickets.all! do |resource|
    if resource[:type] == "question"
      totalLeads += 1
      
    elsif resource[:type] == "task"
      totalQuotes +=1
    else 
      puts "oops error with the zendesk query calculation !"
    end
  end 
  authenticator = IBMWatson::Authenticators::IamAuthenticator.new(
    apikey: ENV["IBM_API_KEY"]
  )
  text_to_speech = IBMWatson::TextToSpeechV1.new(
    authenticator: authenticator
)
  
  text_to_speech.service_url = ENV["IBM_URL"]

  broken_elevators = Elevator.where(status: "inactive").count + Elevator.where(status: "intervention").count
  
  File.open("./public/hello_world.wav", "wb") do |audio_file|
    response = text_to_speech.synthesize(
      text: "
      Hello #{Employee.find_by(user_id:current_user.id).first_name} #{Employee.find_by(user_id:current_user.id).last_name},
      There are currently #{Elevator.count} elevators deployed in the #{Building.count} buildings of your #{Customer.count} customers.
      Currently, #{broken_elevators} elevators are not in Running Status and are being serviced.
      You currently have #{totalQuotes} quotes awaiting processing.
      You currently have #{totalLeads} leads in your contact requests.
      #{Battery.count} Batteries are deployed across #{Address.distinct.count(:city)} cities.",
      accept: "audio/wav",
      voice: "en-GB_KateV3Voice"
    )
    audio_file.write(response.result)
  end %>

<audio controls preload="metadata" style=" width:100%;">
    <source src="/hello_world.wav" type="audio/wav">
    Your browser does not support the audio element.
</audio><br />

app/views/admin/dashboard/_star_wars_facts.html.erb
  <% # STAR WARS FACTS
  require "ibm_watson/authenticators"
  require "ibm_watson/text_to_speech_v1"
  require "httparty"
  require "json"


 randomCounter = rand(1..60)
  randoCounter = rand(1..7)
  sw = HTTParty.get("https://swapi.dev/api/planets/#{randomCounter}/")

  case randoCounter
  when 1
    star_wars_facts = "The diameter of planet #{sw["name"]} is #{sw["diameter"]}"
  when 2
    star_wars_facts = "The rotation period of planet #{sw["name"]} is #{sw["rotation_period"]} hours"
  when 3
    star_wars_facts = "The orbital period of planet #{sw["name"]} is #{sw["orbital_period"]} days"
  when 4
    star_wars_facts = "The gravity of planet #{sw["name"]} is #{sw["gravity"]}"
  when 5
    star_wars_facts = "The population of planet #{sw["name"]} is #{sw["population"]}"
  when 6
    star_wars_facts = "The climate of planet #{sw["name"]} is #{sw["climate"]}"
  when 7
    star_wars_facts = "The terrain of planet #{sw["name"]} is #{sw["terrain"]}"
  else 
    star_wars_facts = "oops error with random switch case"
  end
    

  authenticator = IBMWatson::Authenticators::IamAuthenticator.new(
    apikey: ENV["IBM_API_KEY"]
  )
  text_to_speech = IBMWatson::TextToSpeechV1.new(
    authenticator: authenticator
)
  text_to_speech.service_url = ENV["IBM_URL"]


  File.open("./public/star_wars_facts.wav", "wb") do |audio_file|
    response = text_to_speech.synthesize(
      text:"#{star_wars_facts}",
      accept: "audio/wav",
      voice: "en-GB_KateV3Voice"
    )
    audio_file.write(response.result)
  end %>

<audio controls preload="metadata" style=" width:100%;">
    <source src="/star_wars_facts.wav" type="audio/wav">
    Your browser does not support the audio element.
</audio><br /> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocket Elevator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" />
		<title>Rocket Elevators - Elevate Safety, Speed and Style</title>
		<meta name="description" content="" />
		<meta name="Author" content="Thomas Simoneau" />
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
		<link href="//db.onlinewebfonts.com/c/0e979bd4a3c1c6ac788ed57ac569667f?family=revicons" rel="stylesheet" type="text/css"/>
		<!-- mobile settings -->
		<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		
		<%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="smoothscroll enable-animation">
	<!-- wrapper -->
		<div id="wrapper">


			<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">
						

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<a class="logo float-left" href="/index">
						<%= image_tag("R2.png", :alt => "") %>
						
						</a>

					
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li><!-- HOME -->
										<a href="/index#home">
											HOME
										</a>
									</li>
									<li><!-- SERVICES -->
										
										<a href="index#services">
											SERVICES
											<ul class="dropdown-menu">
												<li><%= link_to "Residential Building", residential_path%></li>
												<li><%= link_to "For Commercial & Corporate Buildings", corporate_path%></li>
												<li><%= link_to "Request a quote", quote_path%></li>
											</ul>

										</a>
									</li>
									<li><!-- PORTFOLIO -->
										<a href="/index#portfolio">
											PORTFOLIO
										</a>
									</li>
									<li><!-- NEWS -->
										<a href="/index#news">
											NEWS
										</a>
									</li>
									<li><!-- CLIENTS -->
										<a href="/index#clients">
											CLIENTS
										</a>
									</li>
									<li><!-- CONTACT -->
										<a href="/index#contact">
											CONTACT
										</a>
									</li>
										<li><!-- INTERVENTION -->
											<li><%= link_to "INTERVENTION", "/intervention" %></li>
									</li>


									<li><!-- ADMIN -->
										
										<% if user_signed_in? %>
										<a>
										ACCOUNT
											<ul class="dropdown-menu">
												<li><%= link_to "ACCOUNT", edit_user_registration_path %></li>
												<li><%= link_to "LOGOUT", destroy_user_session_path %></li>
												<% if current_user.try(:admin?) %>
													<li><a href="/admin">EMPLOYEES</a></li>
													<li><a href="/blazer">GRAPHS</a></li>
												<% end %>
											</ul>
											
										</a>
										<% else %>
										<a>
										ACCOUNT
											<ul class="dropdown-menu">
												<li><%= link_to "SIGN UP", new_user_registration_path%></li>
												<li><%= link_to "LOGIN", new_user_session_path%></li>
											</ul>
										</a>
										<% end %>
									</li>
								</ul>
							</nav>
						</div>
					</div>
					<% flash.each do |type, msg| %>
					<div class="pl-150 pt-10 alert alert-info">
						<%= msg %>
					</div>
					<% end %>
				</header>
				<!-- /Top Nav -->
			</div>
	
    <%= yield %>
	
	
	
				
		
  </body>
</html>